### ISSUE TITLE
[Azure Repo's] Switch to different AAD for the same identity 

### ISSUE THREAD

**Issue by Manbearpiet** [microsoft/vscode-remote-repositories-github#276] opened 2022-11-21 10:36 UTC
**Problem**

We have multiple Azure AD tenants with separate DevOps organizations. We have guest invites to work cross organizations.
When I try to clone a repository using the **Remote Repositories: Open Remote Repository** from an Azure DevOps organization that is not bound to my users native Azure AD directory, the extension doesn't enumerate tenants before the organizations overview, so it doesn't list the organizations while we do have access to them with the same user.

Orgs bound to AAD 1:
![image](https://user-images.githubusercontent.com/43993129/203028638-e0bf85bf-440c-4357-acb4-7e269f46e7f7.png)

Orgs bound to AAD 2:
![image](https://user-images.githubusercontent.com/43993129/203028421-360fd8dd-f31d-4a8f-8d48-28967a44901f.png)

In the portal when I want to switch to a directory where I've a B2B guest invite I use the: **Switch to another directory** functionality. I hope this helps.

**Potential direction for a fix**

Maybe it's possible to enumerate/allow the user to pick the tenants an identity has access to, so you could pick from which AAD to enumerate the organizations from.

**Comment by joyceerhl** [comment] 2022-11-21 23:23
Duplicate of https://github.com/microsoft/vscode-remote-repositories-github/issues/241

**Closed as not planned by joyceerhl** 2022-11-21 23:23 UTC
