### ISSUE TITLE
Silently does nothing when GitHub Repositories extension is disabled

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode-remote-repositories-github#205] opened 2022-06-29 11:20 UTC
I don't recall why or when I disabled the GitHub Repositories extension but not the Remote Repositories extension. 

1. Disable GitHub Repositories
2. Make sure Remote Repositories is still enabled
3. Run the command "Remote Repositories: Open Remote Repository..." and choose a GitHub repo
4. Nothing appears to happen. Nothing in logs, nothing in the console.

**Comment by joyceerhl** [comment] 2022-07-11 19:56
Duplicate of https://github.com/microsoft/vscode-remote-repositories-github/issues/193

**Closed by joyceerhl** 2022-07-11 19:56 UTC
Labels: bug
