### ISSUE TITLE
Functionality of Pull Request review for Azure DevOps

### ISSUE THREAD

**Issue by TestingD-BALTA** [microsoft/vscode-remote-repositories-github#415] opened 2024-01-05 14:59 UTC
Please add functionality of performing Pull Requests (review, comment, create) from VSCode. This is very important and largest drawback Azure DevOps comparing to other competitors like GitHub, BitBucket, GitLab - which have very good integration with VSCode.

**Comment by joyceerhl** [comment] 2024-01-05 16:06
Duplicate of https://github.com/microsoft/vscode-remote-repositories-github/issues/282

**Closed as not planned by joyceerhl** 2024-01-05 16:06 UTC
