### ISSUE TITLE
Sometimes PR shows incoming changes (stale)

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode-remote-repositories-github#159] opened 2022-03-10 09:10 UTC
I have not yet figured out how this happens, but I think when I open the same PR multiple times over a week and there have been changes, I see an incoming indication on the PR branch (from the status bar), even though I had just clicked "." on a PR and would expect latest changes to appear.

This goes away when I reload the window with caches disabled.

I think this kind of stale view makes PR reviews hard because you maybe reviewing the wrong thing.

**Comment by joyceerhl** [comment] 2022-03-14 17:33
I can also repro--closing the tab before bringing the branch up to speed seems to be key. RemoteHub finds that we are behind and does a fast forward:

```ts
[2022-03-11 08:43:47:657] Fast forward to d0e25acf7f92be0028e51353be1768d459be0103; rootUri=vscode-vfs://github%2B7b2276223a312c22726566223a7b2274797065223a332c226964223a22313936227d7d/alexr00/playground
```

But for some reason this doesn't actually fast forward the file tree contents. Will investigate further.

**Comment by joyceerhl** [comment] 2022-03-31 02:37
I cannot reproduce this anymore in github.dev today--does it still repro for you @bpasero / @alexr00?

**Comment by bpasero** [comment] 2022-03-31 05:18
@joyceerhl yes it reproduces for me with the steps in https://github.com/microsoft/vscode-remote-repositories-github/issues/159#issuecomment-1064904115

![image](https://user-images.githubusercontent.com/900690/160981801-4871c65b-a885-4d3a-9589-22ef5203968f.png)

**Closed** 2022-12-14 01:41 UTC
Labels: bug, info-needed, pull-requests, important
