### ISSUE TITLE
Not letting me upload/connect repository

### ISSUE THREAD

**Issue by error404unreachable** [microsoft/vscode-remote-repositories-github#321] opened 2023-04-05 22:03 UTC
It’s not loading the code space or anything, and most importantly not letting me connect my GitHub repository. It was working just fine a day ago. I don’t know what happened, and no one said about vscode.dev being down, and I have refreshed, closed and opened, and even hard-reset on my device. After all that it is still not working :(    If any vs code devs could fix this, that would make me really happy.

**Comment by joyceerhl** [comment] 2023-04-05 23:38
@error404unreachable are you using a GitHub Codespace or using vscode.dev? A GIF or screenshot of what you're seeing would be helpful.

**Comment by error404unreachable** [comment] 2023-04-06 12:45
vscode.dev
I press remote repository but it just says activating extensions and does nothing:
![IMG_1790](https://user-images.githubusercontent.com/126827750/230382141-887775d3-8714-40c6-a66e-4b65b9700115.png)

**Comment by joyceerhl** [comment] 2023-04-06 15:31
@error404unreachable I cannot reproduce the reported behavior, I see this:
![image](https://user-images.githubusercontent.com/30305945/230426409-eeed7eab-c7a6-4ea8-805b-949ce8a61b97.png)

Could you please try a couple things:
1. Make sure that the GitHub Repositories and Remote Repositories extensions are installed and enabled. 
  ![image](https://user-images.githubusercontent.com/30305945/230426529-74581648-b66c-4141-84c4-da354dc0921c.png)
2. If they are installed and enabled, please try opening the developer tools console (ctrl+shift+i on Windows) and share any errors you might see there.
3. Does accessing a specific repository link (e.g. vscode.dev/github/microsoft/vscode) work for you?
4. Does selecting Open Remote Repository in insiders.vscode.dev (using VS Code Insiders) work for you?

**Comment by error404unreachable** [comment] 2023-04-06 17:09
Yeah I tried both insiders and specific repository but it just keeps on loading and not letting me use repository same with GitHub.dev
![IMG_1794](https://user-images.githubusercontent.com/126827750/230448356-16c2dc0c-5389-44e1-94e3-b1453ee3c65f.jpeg)
![IMG_1793](https://user-images.githubusercontent.com/126827750/230448365-fcf60259-93c0-4b13-a323-3629f82e0a87.png)

**Comment by error404unreachable** [comment] 2023-04-06 17:10
Also I’m on mobile so maybe that’s the reason

**Comment by error404unreachable** [comment] 2023-04-06 17:12
Also:
![IMG_1795](https://user-images.githubusercontent.com/126827750/230448848-40018569-6a6e-4408-96d9-002284732ed1.png)

**Comment by joyceerhl** [comment] 2023-04-06 17:26
This should work on mobile. Are you possibly behind a network proxy? Can you share the developer tools console contents if there are errors there?

**Comment by error404unreachable** [comment] 2023-04-06 17:44
Only a school firewall

**Comment by joyceerhl** [comment] 2023-04-06 17:45
It's very likely that your firewall disallows network requests which are required for vscode.dev to work. Can you please share the developer tools console contents so we can identify which requests are being blocked?

**Comment by error404unreachable** [comment] 2023-04-06 18:33
It was working a few days ago…

**Comment by error404unreachable** [comment] 2023-04-06 18:34
Also how do you access the dev tools on mobile?

**Comment by joyceerhl** [comment] 2023-04-06 18:41
Do you remember the last time that it worked for you? Is it possible that the firewall rules were recently updated?

Which browser are you using? From your screenshot above, you may be able to access the dev tools by clicking on the three dots in the top right corner of your browser and selecting More tools > Developer tools.

**Comment by error404unreachable** [comment] 2023-04-06 18:41
Chrome

**Comment by error404unreachable** [comment] 2023-04-06 18:47
Yeah there’s not dev tools here

**Comment by error404unreachable** [comment] 2023-04-07 12:32
What’s weird it’s only not working for me. There was one other person using the same site yesterday and it was perfectly fine for him.

**Comment by joyceerhl** [comment] 2023-04-07 16:54
@error404unreachable are you able to try this out with a different browser?

**Comment by error404unreachable** [comment] 2023-04-07 16:59
Yeah safari works

**Comment by error404unreachable** [comment] 2023-04-07 18:26
But only chrome doesn’t that’s weird

**Comment by joyceerhl** [comment] 2023-12-05 18:46
Sorry for the delay, @error404unreachable does this still repro for you?

**Comment by error404unreachable** [comment] 2023-12-06 15:28
I tried it again and it worked :D

**Comment by joyceerhl** [comment] 2023-12-06 17:34
Thanks for the update! Closing as not reproducible. Please reopen or refile if this persists.

**Closed as not planned by joyceerhl** 2023-12-06 17:34 UTC
Labels: info-needed
