### ISSUE TITLE
cannot remotly open repos

### ISSUE THREAD

**Issue by ChubbyDogeCoder** [microsoft/vscode-remote-repositories-github#210] opened 2022-07-11 00:03 UTC
Issue Type: <b>Bug</b>

I find the remote repo, but when I click on it nothing happnes, and Idk why. This was the case since i installed it couple of weeks ago

Extension version: 0.14.0
VS Code version: Code 1.69.0 (92d25e35d9bf1a6b16f7d0758f25d48ace11e5b9, 2022-07-07T05:28:36.503Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No

**Comment by joyceerhl** [comment] 2022-07-11 18:13
@ChubbyDogeCoder please try updating to v0.16.0 of the extension. If that doesn't help, would you mind sharing the contents of the developer console if there are any warnings or errors there? Could you please provide a screen recording of the steps you are taking using gifcap.dev? Thank you!

**Comment by wweiss** [comment] 2022-07-21 14:17
I am having the exact same issue. NOTHING happens.  Nothing in debug.  Nothing to indicate and issue other than no result ;)

1. Open the `Remote Explorer`
2. Under `Remote Repositories` click `Open Remote Repository`
3. Click `Open Repository from GitHub`
4. Wait while list populates and click on a repository.
5. Watch nothing happen.

VSCode: 1.69.2
Remote Repositories: 0.16.0

**Comment by joyceerhl** [comment] 2022-07-21 21:15
@wweiss Yep, this sounds like a duplicate of https://github.com/microsoft/vscode-remote-repositories-github/issues/193. The pre-releases of Remote Repositories should prompt the user to install GitHub Repositories as well; we will also publish a stable build with the fix at the end of the month. Sorry for the confusion!

**Comment by joyceerhl** [comment] 2022-12-06 17:16
Closing as duplicate of https://github.com/microsoft/vscode-remote-repositories-github/issues/193

**Closed by joyceerhl** 2022-12-06 17:16 UTC
Labels: bug, info-needed
