### ISSUE TITLE
File path in file picker displays owner/repo - causes picker to get stuck when you backspace to owner

### ISSUE THREAD

**Issue by TylerLeonhardt** [microsoft/vscode-remote-repositories-github#150] opened 2022-03-04 21:35 UTC
* Open file picker (cmd/ctrl+O)
* notice it shows the owner & repo in the filepath:
![image](https://user-images.githubusercontent.com/2644648/156844534-d82620ad-df90-4d8b-9518-39c0f0f470f8.png)
* backspace all the way to `TylerLeonhard`
* Now try typing the path back in

I noticed that the picker ends up getting stuck with a "path does not exist" item and clicking on items doesn't have any affect.

**Comment by joyceerhl** [comment] 2022-03-04 22:12
I recall you had trouble reproing. Is this the scenario you saw:

1. Open https://github.com/TylerLeonhardt/codeswings
2. Open Folder
3. :bug: folder picker gets stuck with 
![image](https://user-images.githubusercontent.com/30305945/156848800-be6ada41-37cd-406b-aa3e-b1896e9ba0df.png)


```
[2022-03-04 22:09:34:396] [RemoteHub] [c:\Users\huer\Source\Repos\vscode-remotehub\extensions\remotehub\dist\extension.js:13273:19]() GraphqlResponseError: Request failed due to following response errors:
 - Could not resolve to a Repository with the name '/undefined'.
	at [c:\Users\huer\Source\Repos\vscode-remotehub\extensions\remotehub\node_modules\]()@octokit\graphql\dist-web\index.js:74:1
	at processTicksAndRejections (<node_internals>/internal/process/task_queues.js:93:5)
	at async GitHubRepositoryProvider.graphql ([c:\Users\huer\Source\Repos\vscode-remotehub\extensions\remotehub\src\github\provider.ts:410:11]())
	at async GitHubRepositoryProvider.getRepositoryInfo ([c:\Users\huer\Source\Repos\vscode-remotehub\extensions\remotehub\src\github\provider.ts:3512:18]())
	at async GitHubRepositoryProvider.createMetadata ([c:\Users\huer\Source\Repos\vscode-remotehub\extensions\remotehub\src\github\provider.ts:492:17]())
	at async _VirtualProviderService.getMetadataCore ([c:\Users\huer\Source\Repos\vscode-remotehub\extensions\remotehub\src\providers.ts:921:22]())
	at async _VirtualProviderService.getMetadata ([c:\Users\huer\Source\Repos\vscode-remotehub\extensions\remotehub\src\providers.ts:864:20]())
	at async GitHubRepositoryProvider.getFileTree ([c:\Users\huer\Source\Repos\vscode-remotehub\extensions\remotehub\src\github\provider.ts:1740:32]())
	at async GitHubFS.stat ([c:\Users\huer\Source\Repos\vscode-remotehub\extensions\remotehub\src\github\fs.ts:179:17]())
	at async ChangeTrackingFileSystem.stat ([c:\Users\huer\Source\Repos\vscode-remotehub\extensions\remotehub\dist\extension.js:23570:14]()) {request: {…}, headers: {…}, response: {…}, name: 'GraphqlResponseError', errors: Array(1), …}
```

**Comment by joyceerhl** [comment] 2022-12-06 17:49
Duplicate of https://github.com/microsoft/vscode/issues/144702

**Closed by joyceerhl** 2022-12-06 17:49 UTC
Labels: bug
