### ISSUE TITLE
Authenticate to different (enterprise) Github instance

### ISSUE THREAD

**Issue by zook-unity** [microsoft/vscode-remote-repositories-github#9] opened 2021-06-14 17:22 UTC
As a developer I would like to authenticate to an enterprise github provider so that I can use remote repositories with my work code. When I authenticate I want to specify which github to log into to search for remote repositories. Currently I'm authenticated to the public general "github" account but cannot use remote repositories to view code from a different github provider.

**Comment by GitMensch** [comment] 2021-06-14 19:29
duplicate of #4

**Closed** 2021-06-15 20:38 UTC
Labels: *duplicate
