### ISSUE TITLE
Allow repos to be added to an existing workspace

### ISSUE THREAD

**Issue by asampal** [microsoft/vscode-remote-repositories-github#160] opened 2022-03-12 04:33 UTC
I have a workspace where I've added one repo. I would now like to add another repo to the same workspace, but when I try and open it, my current workspace closes and the newly opened repo appears in a non-workspace window. From browsing the issues on this project, it appears that at one point, opening a repo did not do so in a new window, but this ability was added later. Both options should be available, IMO.

GitHub Repositories v0.27.2022031001

Version: 1.66.0-insider (user setup)
Commit: 6b7453421201c888b81eae5c04ec822a6423608f
Date: 2022-03-11T05:17:19.559Z
Electron: 17.1.1
Chromium: 98.0.4758.109
Node.js: 16.13.0
V8: 9.8.177.11-electron.0
OS: Windows_NT x64 10.0.22000

**Comment by joyceerhl** [comment] 2022-12-08 22:33
Duplicate of https://github.com/microsoft/vscode/issues/144702

**Closed by joyceerhl** 2022-12-08 22:33 UTC
Labels: feature-request
