### ISSUE TITLE
Continuing working on fails with parsing error 

### ISSUE THREAD

**Issue by meganrogge** [microsoft/vscode-remote-repositories-github#335] opened 2023-06-01 15:50 UTC
Have some changes [changedFiles.zip](https://github.com/microsoft/vscode-remote-repositories-github/files/11627241/changedFiles.zip)

Run this command

![Screenshot 2023-06-01 at 10 49 50 AM](https://github.com/microsoft/vscode-remote-repositories-github/assets/29464607/f77bb403-ea78-4eed-99b6-e594f49b5faa)

See this notification

![Screenshot 2023-06-01 at 10 48 19 AM](https://github.com/microsoft/vscode-remote-repositories-github/assets/29464607/9a5b4018-df84-4e37-b169-22a11881786f)

cc @joyceerhl

**Comment by sandy081** [comment] 2023-06-01 15:59
@meganrogge Any reason why this is assigned to me?

**Comment by meganrogge** [comment] 2023-06-01 16:16
@joyceerhl had suggested this would be your domain 🤷🏼‍♀️

**Comment by joyceerhl** [comment] 2023-06-01 16:46
@meganrogge no, I was referring to the fact that you had Remote Repositories mysteriously disabled in your local VS Code client

**Comment by joyceerhl** [comment] 2023-06-01 16:59
Duplicate of https://github.com/microsoft/vscode/issues/162462

**Closed as not planned by joyceerhl** 2023-06-01 16:59 UTC
