### ISSUE TITLE
Modal prompt loop when navigating to non-existent repository

### ISSUE THREAD

**Issue by chrisdias** [microsoft/vscode-remote-repositories-github#213] opened 2022-07-12 16:15 UTC
When you try to navigate to a non-existent repository (e.g., https://vscode.dev/github/microsoft/vscodeeeeeeeeeee) you are notified (modally) that the repo doesn't exist and give the opportunity to open another one. When you click on "Open Repository, a quick pick opens but the error message is presented to you again (modally).  
 
![image](https://user-images.githubusercontent.com/1487073/178522330-39a73886-48b8-4e79-bd84-c74734d7f8ad.png)

I would expect that when clicking `Open Repository` the dialog goes away and I can proceed with the quick pick.

**Comment by andreamah** [comment] 2022-07-28 21:21
I'm getting this error every time that I try to use a remote URL:

<img width="426" alt="image" src="https://user-images.githubusercontent.com/31675041/181639329-73915d31-c2ec-4c99-ada5-86a10998026f.png">

**Comment by andreamah** [comment] 2022-07-28 21:25
> I'm getting this error every time that I try to use a remote URL:
> 
> <img alt="image" width="426" src="https://user-images.githubusercontent.com/31675041/181639329-73915d31-c2ec-4c99-ada5-86a10998026f.png">
> 
> I have the extension installed, so I'm not too sure why it's doing this?

update: I think that this is somewhat of a duplicate of [#219](https://github.com/microsoft/vscode-remote-repositories-github/issues/219)?

**Comment by joyceerhl** [comment] 2022-07-28 21:38
@andreamah yeah that's a separate issue--for this particular bug, verification steps should be:
1. Go to https://insiders.vscode.dev/github/microsoft/vscodeeeeeeeeeee
2. Verify that you get a modal dialog about the repository being invalid
3. Verify that if you click on the Open Repository action on the modal dialog, you don't get a cascade of modal dialogs, and you can use the Open Repository picker to switch to a different repo 
![image](https://user-images.githubusercontent.com/30305945/181642094-281eef74-40e7-4da6-9bdf-ab499eecd31d.png)

**Closed by joyceerhl** 2022-07-28 21:38 UTC
Labels: bug, verification-found
