### ISSUE TITLE
Clicking a search result fails to open the matched line

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode-remote-repositories-github#98] opened 2021-12-10 10:38 UTC
1. Open https://vscode.dev/github/microsoft/vscode-generator-code
2. Search for `code-insiders`, without indexing
3. Click the first search result, in `README.md`

The file opens correctly, but 🐛 the cursor stays in line 1, instead of line 61

**Comment by joyceerhl** [comment] 2021-12-10 16:26
This is a known limitation and is currently expected behavior without indexing, because GitHub doesn't give us any line info for their API-based search.

**Comment by joyceerhl** [comment] 2022-12-06 17:58
Closing as we can't do anything about this with the current GitHub search API. We can revisit once the new code search API becomes available.

**Closed by joyceerhl** 2022-12-06 17:58 UTC
Labels: bug, search, upstream, github
