### ISSUE TITLE
fail to use `go to definition` when physical path requires a resolver

### ISSUE THREAD

**Issue by unbyte** [microsoft/vscode-remote-repositories-github#19] opened 2021-06-16 04:47 UTC
e.g.

```javascript
import foo from './foo'
```

In local repositories, vscode can know the physical path is `./foo.js` or `./foo.ts`. 
But with this plugin it will throw `Unable to open 'foo': Unable to read file 'vscode-vfs://github/**/foo' (Error: Unable to resolve non-existing file 'vscode-vfs://github/**/foo').`

**Comment by eamodio** [comment] 2021-06-21 21:04
@mjbvz Is there something we can do here with the single-file language service for TypeScript?

**Comment by jianboy** [comment] 2021-06-23 10:24
=======================================
**Give you a tip. you can refer to the gihtub1s to implement it.**

![动画 (1)](https://user-images.githubusercontent.com/11532015/123081120-3238fd80-d450-11eb-87e6-9811aea516a2.gif)



=======================================

**Comment by unbyte** [comment] 2021-06-23 10:39
> =======================================
> **Give you a tip. you can refer to the [gihtub1s](https://github1s.com/conwnet/github1s) to implement it.**
> 
> ![动画 (1)](https://user-images.githubusercontent.com/11532015/123081120-3238fd80-d450-11eb-87e6-9811aea516a2.gif)
> 
> =======================================

😁 I've been using it since it was published and it works well. I just want to see this plugin provided by Github and Vscode official teams works well too.

**Comment by mjbvz** [comment] 2021-06-29 18:26
@eamodio What should the path to `foo` look like in this case? Is it just missing the file extension?

/cc @amcasey

**Comment by eamodio** [comment] 2021-06-29 19:13
@mjbvz I would think `<workspace-folder-path>/foo.js|ts>`

**Comment by amcasey** [comment] 2021-06-29 19:57
There are actually quite a few [file extensions](https://github.com/VincentBailly/TypeScript/blob/cbe56706098438edf744f1922ba6ba76ea821ba1/src/compiler/moduleNameResolver.ts#L1090) to check, but I don't think you have to worry about path mappings or anything like that when it's unambiguously a relative path.

**Comment by joyceerhl** [comment] 2022-12-06 21:46
Duplicate of https://github.com/microsoft/vscode/issues/146853

**Closed by joyceerhl** 2022-12-06 21:46 UTC
