### ISSUE TITLE
Need this support for github.ibm.com

### ISSUE THREAD

**Issue by rdboenig** [microsoft/vscode-remote-repositories-github#169] opened 2022-03-17 20:58 UTC
Hello,
I am using the enterprise version of GitHub with github.ibm.com.  This extension appears to only allow me to access github.com.  Is there another extension available that will allow me to access github.ibm.com?
Thanx, David

**Comment by rdboenig** [comment] 2022-03-17 21:21
I should note I have added Github-enterprise: Uri with github.ibm.com.  No change in results.  I have also tried specifying directly in the command palette under Open remote repositories, but nothing happens

**Comment by joyceerhl** [comment] 2022-03-17 21:26
Thank you for filing an issue. Closing as a duplicate of https://github.com/microsoft/vscode-remote-repositories-github/issues/4. This extension doesn't currently support working with private GHES instances--feel free to upvote that other issue to indicate support for this feature request.

**Closed by joyceerhl** 2022-03-17 21:26 UTC

**Comment by rdboenig** [comment] 2022-03-17 21:31
That is strange since according to the following it does:
https://github.com/microsoft/vscode/pull/115940

**Comment by joyceerhl** [comment] 2022-03-17 21:36
https://github.com/microsoft/vscode/pull/115940 refers to the GitHub authentication extension which is built into VS Code itself. This extension is the GitHub Repositories extension, which is not built into VS Code, and which uses the GitHub authentication extension to obtain authentication sessions.
