### ISSUE TITLE
Open Repository Quick Pick should show current Github user's repos at the top of the list on first launch

### ISSUE THREAD

**Issue by bhavyaus** [microsoft/vscode-remote-repositories-github#272] opened 2022-11-18 18:11 UTC
Currently, on adding a remote github repo for the first time, the list includes repositories who's ordering appears random 
<img width="882" alt="image" src="https://user-images.githubusercontent.com/25044782/202773725-ceb0391d-8bb4-4f28-ab98-e905e5c06278.png">

Subsequent remote repository additions appear to show a filtered list:
<img width="387" alt="image" src="https://user-images.githubusercontent.com/25044782/202773986-993a4754-5efa-46f2-a320-69b8a811bc31.png">

**Comment by joyceerhl** [comment] 2022-11-18 18:23
Duplicate of https://github.com/microsoft/vscode/issues/163603

**Closed as not planned by joyceerhl** 2022-11-18 18:23 UTC
