### ISSUE TITLE
I shouldn't need SAML for all of my organizations In order to use the quickpick experience

### ISSUE THREAD

**Issue by TylerLeonhardt** [microsoft/vscode-remote-repositories-github#95] opened 2021-12-03 16:49 UTC
## Steps

> NOTE: You need a fresh non-SAML'd session

* choose the open repository from GitHub
![image](https://user-images.githubusercontent.com/2644648/144640546-f3b06597-6e0d-43e2-add7-15531fd01c7b.png)
* Get prompted for Auth
* DON'T SAML ANYTHING - in otherwords, you just wanna see your personal repos

### Expected

I see best effort results (just personal repos)

### Actual

I get the error notification to SAML

### Proposal

maybe show a QPI that says: “$(warning) you have not SAML’d for at least one org so results are a subset” kind of thing

**Comment by joyceerhl** [comment] 2022-02-28 23:59
Closing as duplicate of https://github.com/microsoft/vscode-remote-repositories-github/issues/113, which was addressed in the February release.

**Closed by joyceerhl** 2022-02-28 23:59 UTC
