### ISSUE TITLE
Expose access to the IGit interface or to the richer virtual provider model for accessing Git information about remote repos

### ISSUE THREAD

**Issue by eamodio** [microsoft/vscode-remote-repositories-github#168] opened 2022-03-17 06:05 UTC
Currently GitLens "reimplements" a lot of the same functionality RemoteHub does to provide it with the Git data for the virtual repositories. It would be great if more (if not all) of this functionality could be exposed by RemoteHub, either through the IGit interface or better yet via the richer virtual provider model. 

This would allow GitLens (and other extensions) access to the Git data without each having to re-implement it (which would also help avoid rate limit issues as well). This would also allow GitLens (and other extensions) to work with Azure Repos too, whereas right now GitLens only has support for GitHub repositories.

**Comment by joyceerhl** [comment] 2022-12-08 22:42
Duplicate of https://github.com/microsoft/vscode-remote-repositories-github/issues/101

**Closed by joyceerhl** 2022-12-08 22:42 UTC
Labels: api, feature-request
