### ISSUE TITLE
Unable to see the latest change in the PR view in Edge browser

### ISSUE THREAD

**Issue by yujincat** [microsoft/vscode-remote-repositories-github#111] opened 2022-01-24 01:56 UTC
When opening a GitHb PR in the web editor using Edge browser, the file diff view does not show the latest change of the PR branch. 

For [example](https://github.dev/yujincat/hello-github-actions/pull/5), I added a new file in the existing PR but it does not show up under `Files` 
![image](https://user-images.githubusercontent.com/55138573/150709824-7f964ed0-22fd-4d55-b6a1-ad4605731e6d.png)

Here is the debug information: 

ChangeStore Operations for vscode-vfs://
```
ChangeStore Operations for vscode-vfs://github+7b2276223a312c22726566223a7b2274797065223a332c226964223a2235227d7d/yujincat/hello-github-actions

{"schemaVersion":1,"operations":[]}
```

Remote Repositories: 
```
Remote Repositories

{"schemaVersion":1,"workspaceRepositories":[["-70fd1281/vscode-vfs://github%2B7b2276223a312c22726566223a7b2274797065223a332c226964223a223130353835227d7d/github/actions-dotnet",{"workspaceId":"-70fd1281","uri":{"$mid":1,"path":"/github/actions-dotnet","scheme":"vscode-vfs","authority":"github+7b2276223a312c22726566223a7b2274797065223a332c226964223a223130353835227d7d"},"canonicalUri":{"$mid":1,"path":"/github/actions-dotnet","scheme":"vscode-vfs","authority":"github"},"name":"github/actions-dotnet","provider":{"id":"github","name":"GitHub"},"ref":{"type":0,"name":"main"},"pullRequest":{"id":"10585"},"timestamp":1639176835076}],["-7b11ed8b/vscode-vfs://github/github/actions-dotnet",{"workspaceId":"-7b11ed8b","uri":{"$mid":1,"path":"/github/actions-dotnet","scheme":"vscode-vfs","authority":"github"},"canonicalUri":{"$mid":1,"path":"/github/actions-dotnet","scheme":"vscode-vfs","authority":"github"},"name":"github/actions-dotnet","provider":{"id":"github","name":"GitHub"},"ref":{"type":0,"name":"main"},"changes":{"added":0,"changed":1,"deleted":0,"timestamp":1641448487442},"timestamp":1641448487442}],["-14b78744/vscode-vfs://github%2B7b2276223a312c22726566223a7b2274797065223a342c226964223a2279756a696e6361742f6e6f6e2d6e756c6c2d6a6f6272657175657374227d7d/github/actions-dotnet",{"workspaceId":"-14b78744","uri":{"$mid":1,"path":"/github/actions-dotnet","scheme":"vscode-vfs","authority":"github+7b2276223a312c22726566223a7b2274797065223a342c226964223a2279756a696e6361742f6e6f6e2d6e756c6c2d6a6f6272657175657374227d7d"},"canonicalUri":{"$mid":1,"path":"/github/actions-dotnet","scheme":"vscode-vfs","authority":"github"},"name":"github/actions-dotnet","provider":{"id":"github","name":"GitHub"},"ref":{"type":0,"name":"yujincat/non-null-jobrequest"},"timestamp":1639176831525}],["278f00d4/vscode-vfs://github/github/github",{"workspaceId":"278f00d4","uri":{"$mid":1,"path":"/github/github","scheme":"vscode-vfs","authority":"github"},"canonicalUri":{"$mid":1,"path":"/github/github","scheme":"vscode-vfs","authority":"github"},"name":"github/github","provider":{"id":"github","name":"GitHub"},"ref":{"type":0,"name":"master"},"timestamp":1641889564237}],["-65178f8b/vscode-vfs://github%2B7b2276223a312c22726566223a7b2274797065223a332c226964223a22323033353132227d7d/github/github",{"workspaceId":"-65178f8b","uri":{"$mid":1,"path":"/github/github","scheme":"vscode-vfs","authority":"github+7b2276223a312c22726566223a7b2274797065223a332c226964223a22323033353132227d7d"},"canonicalUri":{"$mid":1,"path":"/github/github","scheme":"vscode-vfs","authority":"github"},"name":"github/github","provider":{"id":"github","name":"GitHub"},"ref":{"type":0,"name":"yujincat/cmw-editor-ghes"},"pullRequest":{"id":"203512"},"changes":{"added":0,"changed":1,"deleted":0,"timestamp":1639459021764},"timestamp":1639459021764}],["2fa708a4/vscode-vfs://github/github/launch",{"workspaceId":"2fa708a4","uri":{"$mid":1,"path":"/github/launch","scheme":"vscode-vfs","authority":"github"},"canonicalUri":{"$mid":1,"path":"/github/launch","scheme":"vscode-vfs","authority":"github"},"name":"github/launch","provider":{"id":"github","name":"GitHub"},"ref":{"type":0,"name":"master"},"timestamp":1641542343136}],["2d775f2/vscode-vfs://github%2B7b2276223a312c22726566223a7b2274797065223a322c226964223a2231666464363338636636613331613837613139666536616465373261393533656366356236343065227d7d/github/actions-dotnet",{"workspaceId":"2d775f2","uri":{"$mid":1,"path":"/github/actions-dotnet","scheme":"vscode-vfs","authority":"github+7b2276223a312c22726566223a7b2274797065223a322c226964223a2231666464363338636636613331613837613139666536616465373261393533656366356236343065227d7d"},"canonicalUri":{"$mid":1,"path":"/github/actions-dotnet","scheme":"vscode-vfs","authority":"github"},"name":"github/actions-dotnet","provider":{"id":"github","name":"GitHub"},"ref":{"type":3,"name":"1fdd638"},"timestamp":1639560536513}],["-34b33c23/vscode-vfs://github/actions/runner",{"workspaceId":"-34b33c23","uri":{"$mid":1,"path":"/actions/runner","scheme":"vscode-vfs","authority":"github"},"canonicalUri":{"$mid":1,"path":"/actions/runner","scheme":"vscode-vfs","authority":"github"},"name":"actions/runner","provider":{"id":"github","name":"GitHub"},"ref":{"type":0,"name":"main"},"timestamp":1639614762737}],["-46cfac02/vscode-vfs://github/github/docs-internal",{"workspaceId":"-46cfac02","uri":{"$mid":1,"path":"/github/docs-internal","scheme":"vscode-vfs","authority":"github"},"canonicalUri":{"$mid":1,"path":"/github/docs-internal","scheme":"vscode-vfs","authority":"github"},"name":"github/docs-internal","provider":{"id":"github","name":"GitHub"},"ref":{"type":0,"name":"main"},"timestamp":1639644958972}],["1248e993/vscode-vfs://github%2B7b2276223a312c22726566223a7b2274797065223a332c226964223a2234383336227d7d/github/launch",{"workspaceId":"1248e993","uri":{"$mid":1,"path":"/github/launch","scheme":"vscode-vfs","authority":"github+7b2276223a312c22726566223a7b2274797065223a332c226964223a2234383336227d7d"},"canonicalUri":{"$mid":1,"path":"/github/launch","scheme":"vscode-vfs","authority":"github"},"name":"github/launch","provider":{"id":"github","name":"GitHub"},"ref":{"type":3,"name":"ef75734"},"pullRequest":{"id":"4836"},"timestamp":1639708972395}],["-f224aaa/vscode-vfs://github%2B7b2276223a312c22726566223a7b2274797065223a332c226964223a2234383636227d7d/github/launch",{"workspaceId":"-f224aaa","uri":{"$mid":1,"path":"/github/launch","scheme":"vscode-vfs","authority":"github+7b2276223a312c22726566223a7b2274797065223a332c226964223a2234383636227d7d"},"canonicalUri":{"$mid":1,"path":"/github/launch","scheme":"vscode-vfs","authority":"github"},"name":"github/launch","provider":{"id":"github","name":"GitHub"},"ref":{"type":0,"name":"yujincat/cmw-ghes-docs"},"pullRequest":{"id":"4866"},"timestamp":1639709255127}],["-754d9a7f/vscode-vfs://github%2B7b2276223a312c22726566223a7b2274797065223a332c226964223a223130373835227d7d/github/actions-dotnet",{"workspaceId":"-754d9a7f","uri":{"$mid":1,"path":"/github/actions-dotnet","scheme":"vscode-vfs","authority":"github+7b2276223a312c22726566223a7b2274797065223a332c226964223a223130373835227d7d"},"canonicalUri":{"$mid":1,"path":"/github/actions-dotnet","scheme":"vscode-vfs","authority":"github"},"name":"github/actions-dotnet","provider":{"id":"github","name":"GitHub"},"ref":{"type":0,"name":"yujincat/calling-no-nwo-no-version"},"pullRequest":{"id":"10785"},"timestamp":1641805625286}],["-497fbcf4/vscode-vfs://github%2B7b2276223a312c22726566223a7b2274797065223a332c226964223a2234393130227d7d/github/launch",{"workspaceId":"-497fbcf4","uri":{"$mid":1,"path":"/github/launch","scheme":"vscode-vfs","authority":"github+7b2276223a312c22726566223a7b2274797065223a332c226964223a2234393130227d7d"},"canonicalUri":{"$mid":1,"path":"/github/launch","scheme":"vscode-vfs","authority":"github"},"name":"github/launch","provider":{"id":"github","name":"GitHub"},"ref":{"type":0,"name":"yujincat/calling-local-workflows"},"pullRequest":{"id":"4910"},"timestamp":1642500608724}],["-111dd33c/vscode-vfs://github/github/dev",{"workspaceId":"-111dd33c","uri":{"$mid":1,"path":"/github/dev","scheme":"vscode-vfs","authority":"github"},"canonicalUri":{"$mid":1,"path":"/github/dev","scheme":"vscode-vfs","authority":"github"},"name":"github/dev","provider":{"id":"github","name":"GitHub"},"ref":{"type":0,"name":"main"},"timestamp":1642642999483}],["6f337b47/vscode-vfs://github%2B7b2276223a312c22726566223a7b2274797065223a342c226964223a226d6173746572227d7d/github/launch",{"workspaceId":"6f337b47","uri":{"$mid":1,"path":"/github/launch","scheme":"vscode-vfs","authority":"github+7b2276223a312c22726566223a7b2274797065223a342c226964223a226d6173746572227d7d"},"canonicalUri":{"$mid":1,"path":"/github/launch","scheme":"vscode-vfs","authority":"github"},"name":"github/launch","provider":{"id":"github","name":"GitHub"},"ref":{"type":0,"name":"master"},"timestamp":1641876697950}],["671b7377/vscode-vfs://github%2B7b2276223a312c22726566223a7b2274797065223a342c226964223a226d6173746572227d7d/github/github",{"workspaceId":"671b7377","uri":{"$mid":1,"path":"/github/github","scheme":"vscode-vfs","authority":"github+7b2276223a312c22726566223a7b2274797065223a342c226964223a226d6173746572227d7d"},"canonicalUri":{"$mid":1,"path":"/github/github","scheme":"vscode-vfs","authority":"github"},"name":"github/github","provider":{"id":"github","name":"GitHub"},"ref":{"type":0,"name":"master"},"timestamp":1641878400416}],["-175b93e5/vscode-vfs://github%2B7b2276223a312c22726566223a7b2274797065223a332c226964223a2234383938227d7d/github/launch",{"workspaceId":"-175b93e5","uri":{"$mid":1,"path":"/github/launch","scheme":"vscode-vfs","authority":"github+7b2276223a312c22726566223a7b2274797065223a332c226964223a2234383938227d7d"},"canonicalUri":{"$mid":1,"path":"/github/launch","scheme":"vscode-vfs","authority":"github"},"name":"github/launch","provider":{"id":"github","name":"GitHub"},"ref":{"type":0,"name":"tauhid621/find_repo_cache"},"pullRequest":{"id":"4898"},"timestamp":1642060999499}],["267cbcd0/vscode-vfs://github%2B7b2276223a312c22726566223a7b2274797065223a332c226964223a2234393233227d7d/github/launch",{"workspaceId":"267cbcd0","uri":{"$mid":1,"path":"/github/launch","scheme":"vscode-vfs","authority":"github+7b2276223a312c22726566223a7b2274797065223a332c226964223a2234393233227d7d"},"canonicalUri":{"$mid":1,"path":"/github/launch","scheme":"vscode-vfs","authority":"github"},"name":"github/launch","provider":{"id":"github","name":"GitHub"},"ref":{"type":0,"name":"tauhid621/internal_actions_obs"},"pullRequest":{"id":"4923"},"timestamp":1642031795854}],["2284217a/vscode-vfs://github%2B7b2276223a312c22726566223a7b2274797065223a332c226964223a22323035373133227d7d/github/github",{"workspaceId":"2284217a","uri":{"$mid":1,"path":"/github/github","scheme":"vscode-vfs","authority":"github+7b2276223a312c22726566223a7b2274797065223a332c226964223a22323035373133227d7d"},"canonicalUri":{"$mid":1,"path":"/github/github","scheme":"vscode-vfs","authority":"github"},"name":"github/github","provider":{"id":"github","name":"GitHub"},"ref":{"type":0,"name":"yujincat/allow-actions-background-job"},"pullRequest":{"id":"205713"},"timestamp":1642988306600}],["70885747/vscode-vfs://github%2B7b2276223a312c22726566223a7b2274797065223a332c226964223a2235227d7d/yujincat/hello-github-actions",{"workspaceId":"70885747","uri":{"$mid":1,"path":"/yujincat/hello-github-actions","scheme":"vscode-vfs","authority":"github+7b2276223a312c22726566223a7b2274797065223a332c226964223a2235227d7d"},"canonicalUri":{"$mid":1,"path":"/yujincat/hello-github-actions","scheme":"vscode-vfs","authority":"github"},"name":"yujincat/hello-github-actions","provider":{"id":"github","name":"GitHub"},"ref":{"type":0,"name":"yujincat-patch-3"},"pullRequest":{"id":"5"},"timestamp":1642989178964}]]}
```

**Comment by joyceerhl** [comment] 2022-03-21 21:36
Possibly duplicate of https://github.com/microsoft/vscode-remote-repositories-github/issues/159

**Comment by joyceerhl** [comment] 2022-12-08 22:37
@yujincat does this still repro for you?

**Closed** 2023-12-04 19:44 UTC
Labels: bug, info-needed
